### ISSUE TITLE
2018

### ISSUE THREAD

**Issue by abelsiqueira** [hacktoberfestcwb/2017#19]
Olá,

Neste Hacktoberfest vocês estão planejando fazer alguma coisa?
Estou tentando organizar alguma coisa aqui: https://github.com/abelsiqueira/hacktoberfest-cwb-2018, mas podemos juntar esforços.

Abraços

**Comment by abelsiqueira** [comment]
Marcando as pessoas que contribuíram segundo o `contributors`

cc @ramiroluz @vanessaromankiv @ellisonleao @BarthJr @elucardoso @joaorafaelm @Auralcat 

Marcamos local e data: 20/10 na UFPR.

**Comment by ellisonleao** [comment]
Se quiser a gente pode fazer o repo 2018 aqui nessa org. Vou te dar o acesso.

**Comment by abelsiqueira** [comment]
Por favor me faça admin pelo menos do meu repositório.
